package com.arcadio;

/**
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
 

 
/**
*
* @author fserna
*/
public enum TelegramTypes {
	ERROR,
    NULL,
    CESTA,
    CREAR_CESTA,
    INSERTAR_NOM_CESTA,//LO HE A�ADIDO YO 19/03/2013
    //INSERTAR_NOMS_CESTA,//LO HE A�ADIDO YO 04/04/2013
    //ELIMINAR_NOM_CESTA, //LO HE A�ADIDO YO 04/04/2013
    //ELIMINAR_CESTA, //LO HE A�ADIDO YO 04/04/2013
    CREAR_MUESTREADOR,
    MUESTREANDO,
    GET_DATOS_MUESTREADOR,
    HABILITAR_MUESTREADOR,
    DESHABILITAR_MUESTREADOR,
    ELIMINAR_MUESTREADOR,
    REGISTRAR,
    GET_PERSISTENTE,
    SET_PERSISTENTE,
    ADD_A_CESTA_PERSISTENTE,
    ADD_A_LOG,
    GET_HORA_FECHA,
    GET_FECHA,
    GET_HORA,
    PASARELA_STOP,
    LEER,
   // LEER_UNA_VAR, //LO HE A�ADIDO YO 04/04/2013
    PING,
    ESCRIBIR,
    LOG,
    STATUS,
    LISTA_NOMBRES,
    LISTA_NOMBRES_NIVEL,
    SUBLISTA_NOMBRES,
    INFO_VARIABLE,
    NOMBRE_CESTA,
    LISTA_NOMBRES_TIPO,
    SUBLISTA_NOMBRES_TIPO,
    LISTA_TIPOS,
    LISTA_NOMBRES_CESTA,
    TIPO_NOMBRE,
    LISTA_NOMBRES_CONFIGURABLES,
    LISTA_NOMBRES_CONFIGURABLES_RESERVADOS,
    SOLICITAR_FICHERO_TEXTO,
    LEER_BLOQUEO,
    ESCRIBIR_BLOQUEO,
    NOTIFICAR_EVENTO,
    IS_NUMERIC,
    ECHO,
    PERIODO_CESTA,
    PROJECT_STOP,
    MAINTENANCE_INFO,
    
	
}